# Generated by Django 5.2.6 on 2025-09-27 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_game_board_move_delete_choice_delete_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="game_id",
        ),
    ]
