# Generated by Django 5.2.6 on 2025-09-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_remove_game_game_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="move",
            index=models.Index(fields=["board", "x", "y"], name="idx_board_xy"),
        ),
        migrations.AddIndex(
            model_name="move",
            index=models.Index(
                fields=["board", "-move_number"], name="idx_board_lastmove_desc"
            ),
        ),
        migrations.AddConstraint(
            model_name="move",
            constraint=models.UniqueConstraint(
                fields=("board", "x", "y"), name="uniq_move_per_intersection"
            ),
        ),
        migrations.AddConstraint(
            model_name="move",
            constraint=models.UniqueConstraint(
                fields=("board", "move_number"), name="uniq_move_number_per_board"
            ),
        ),
    ]
