# Generated by Django 5.2.6 on 2025-09-28 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_move_idx_board_xy_move_idx_board_lastmove_desc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastMoveCache",
            fields=[
                (
                    "board",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="game.board",
                    ),
                ),
                (
                    "move",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="game.move"
                    ),
                ),
            ],
        ),
    ]
