# Generated by Django 5.2.6 on 2025-09-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_lastmovecache"),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="alive",
            field=models.BooleanField(default=True),
        ),
    ]
