# Generated by Django 5.2.6 on 2025-09-29 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_move_alive"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="move",
            name="uniq_move_per_intersection",
        ),
    ]
