# Generated by Django 5.2.6 on 2025-09-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_remove_move_uniq_move_per_intersection"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("ONGOING", "ONGOING"),
                    ("WHITE_WON", "WHITE_WON"),
                    ("BLACK_WON", "BLACK_WON"),
                    ("DRAW", "DRAW"),
                    ("ABORTED", "ABORTED"),
                ],
                default="ONGOING",
                max_length=20,
            ),
        ),
    ]
