# Generated by Django 5.2.6 on 2025-10-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_alter_game_user_black_alter_game_user_white"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="black_captures",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="board",
            name="white_captures",
            field=models.IntegerField(default=0),
        ),
    ]
